name: Node CI

on: [push, pull_request]

jobs:
  test:
    name: NodeJS ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Environment Information
        run: |
          node --version
          npm --version

      - name: npm install & test
        run: npm it
        env:
          CI: true

